# Generated by Django 4.2.20 on 2026-03-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True, verbose_name='文件名')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='文件URL')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='文件描述')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('format', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件格式')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件版本')),
            ],
            options={
                'verbose_name': '下载文件',
                'verbose_name_plural': '下载文件',
                'db_table': 'download_file',
            },
        ),
    ]
