# Generated by Django 4.2.20 on 2026-03-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunnfcdb', '0002_nutrition_alter_downloadfile_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadfile',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='downloadfile',
            old_name='download_count',
            new_name='downloads',
        ),
        migrations.RenameField(
            model_name='downloadfile',
            old_name='file_name',
            new_name='title',
        ),
    ]
