# Generated by Django 4.2.20 on 2026-03-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnfcdb', '0005_news_alter_downloadfile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标题'),
        ),
    ]
