# Generated by Django 4.2.20 on 2026-03-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunnfcdb', '0008_environmentalfactor_gene_institution_region_variety_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutritionData',
        ),
    ]
