# Generated by Django 4.2.20 on 2026-03-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('file_size', models.CharField(max_length=50, verbose_name='文件大小')),
                ('description', models.TextField(blank=True, null=True, verbose_name='文件描述')),
                ('download_url', models.URLField(verbose_name='下载地址')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '下载文件',
                'verbose_name_plural': '下载文件',
                'db_table': 'sesame_download_files',
                'ordering': ['-create_time'],
            },
        ),
    ]
