# Generated by Django 5.0.7 on 2026-06-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesame', '0006_regionalmapsite_regionalenvironmentvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, verbose_name='活动标识')),
                ('event_title', models.CharField(max_length=240, verbose_name='活动名称')),
                ('event_date', models.CharField(blank=True, max_length=120, null=True, verbose_name='活动日期')),
                ('event_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动地点')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('institution', models.CharField(max_length=200, verbose_name='单位/机构')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话')),
                ('attendance_mode', models.CharField(choices=[('online', '线上参会'), ('offline', '线下参会'), ('undecided', '待确定')], default='undecided', max_length=20, verbose_name='参会方式')),
                ('participant_count', models.PositiveIntegerField(default=1, verbose_name='参会人数')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待联系'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='处理状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '参会意向',
                'verbose_name_plural': '参会意向',
                'db_table': 'sesame_event_registrations',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['event_id', 'email'], name='sesame_even_event_i_2792dd_idx'), models.Index(fields=['status', 'create_time'], name='sesame_even_status_151c03_idx')],
            },
        ),
    ]
