# Generated by Django 4.2.20 on 2026-04-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaxdb', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_scrolling',
            field=models.BooleanField(default=False, verbose_name='是否滚动显示'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='封面图片'),
        ),
    ]
