# Generated by Django 4.2.20 on 2026-03-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnfcdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='营养名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='营养描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '营养',
                'verbose_name_plural': '营养',
                'db_table': 'nutrition',
            },
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='文件名'),
        ),
    ]
