# Generated by Django 5.2.12 on 2026-03-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunnfcdb', '0003_rename_desc_downloadfile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadfile',
            name='file_url',
        ),
    ]
