# Generated by Django 4.2.20 on 2026-03-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnfcdb', '0004_remove_downloadfile_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('image', models.URLField(blank=True, null=True, verbose_name='封面图片')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='标签')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'db_table': 'news',
                'ordering': ['-publish_time', '-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='downloadfile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='文件大小'),
        ),
    ]
