# Generated by Django 4.2.20 on 2026-03-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnfcdb', '0006_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='更新内容')),
                ('changes', models.JSONField(default=list, verbose_name='变更列表')),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '更新记录',
                'verbose_name_plural': '更新记录',
                'db_table': 'changelog',
                'ordering': ['-release_date'],
            },
        ),
    ]
