# Generated by Codex for research database features
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perilla', '0004_news_is_scrolling_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=100, verbose_name='样品编号')),
                ('oil_content', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='含油量(%)')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='蛋白质(%)')),
                ('fatty_acid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='特征脂肪酸(%)')),
                ('lignan', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='特征营养成分')),
                ('moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='水分(%)')),
                ('method', models.CharField(default='HPLC/NIR', max_length=100, verbose_name='检测方法')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='检测日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_records', to='perilla.variety', verbose_name='品种')),
            ],
            options={
                'verbose_name': '营养数据',
                'verbose_name_plural': '营养数据',
                'db_table': 'perilla_nutrition_data',
                'ordering': ['-test_date', 'sample_code'],
                'unique_together': {('variety', 'sample_code')},
            },
        ),
    ]
