# Generated by Django 4.2.20 on 2026-05-29 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perilla', '0005_nutritiondata_research_endpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalMapSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='试验点名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='试验点代码')),
                ('province', models.CharField(max_length=80, verbose_name='地图省份名称')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='纬度')),
                ('trait', models.CharField(blank=True, max_length=150, null=True, verbose_name='优势性状')),
                ('component', models.CharField(blank=True, max_length=150, null=True, verbose_name='功能成分')),
                ('soil', models.CharField(blank=True, max_length=150, null=True, verbose_name='土壤类型')),
                ('display_order', models.IntegerField(default=0, verbose_name='展示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_sites', to='perilla.region', verbose_name='关联区域')),
                ('varieties', models.ManyToManyField(blank=True, related_name='regional_map_sites', to='perilla.variety', verbose_name='优势品种')),
            ],
            options={
                'verbose_name': '区域优势地图点',
                'verbose_name_plural': '区域优势地图点',
                'db_table': 'perilla_regional_map_sites',
                'ordering': ['display_order', 'province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegionalEnvironmentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最小值')),
                ('value_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最大值')),
                ('display_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='展示值')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_values', to='perilla.environmentalfactor', verbose_name='环境因子')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_values', to='perilla.regionalmapsite', verbose_name='地图点')),
            ],
            options={
                'verbose_name': '区域环境因子值',
                'verbose_name_plural': '区域环境因子值',
                'db_table': 'perilla_regional_environment_values',
                'ordering': ['site__display_order', 'factor__category', 'factor__name'],
                'unique_together': {('site', 'factor')},
            },
        ),
    ]
