# Generated by Django 4.2.20 on 2026-03-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaxdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images\\{filename}_news_{id}', verbose_name='封面图片'),
        ),
    ]
