# Generated by Django 5.0.7 on 2026-06-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flaxdb', '0006_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_trait', models.CharField(blank=True, max_length=200, null=True, verbose_name='目标性状/通路')),
                ('association_type', models.CharField(choices=[('coexpression', '共表达'), ('gwas', 'GWAS关联'), ('pathway', '通路关联'), ('ppi', '蛋白互作'), ('literature', '文献证据'), ('trait', '性状关联')], default='coexpression', max_length=50, verbose_name='关联类型')),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='置信度')),
                ('p_value', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='P值')),
                ('effect_size', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='效应值')),
                ('evidence_source', models.CharField(blank=True, max_length=200, null=True, verbose_name='证据来源')),
                ('description', models.TextField(blank=True, null=True, verbose_name='关联说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_associations', to='flaxdb.gene', verbose_name='源基因')),
                ('target_gene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_associations', to='flaxdb.gene', verbose_name='目标基因')),
            ],
            options={
                'verbose_name': '基因关联',
                'verbose_name_plural': '基因关联',
                'db_table': 'flaxdb_gene_associations',
                'ordering': ['-confidence_score', 'source_gene__gene_id'],
                'indexes': [models.Index(fields=['source_gene', 'association_type'], name='flaxdb_gene_source__4adcd7_idx'), models.Index(fields=['is_active', 'confidence_score'], name='flaxdb_gene_is_acti_3f5287_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='geneassociation',
            constraint=models.UniqueConstraint(fields=('source_gene', 'target_gene', 'target_trait', 'association_type'), name='flaxdb_unique_gene_association'),
        ),
    ]
